/**
 * Centralized ID constants and generators for Teaming24 frontend.
 *
 * All agent IDs, task IDs, and entity identifiers should be referenced
 * through this module to ensure consistency with the backend.
 *
 * ID Format Rules:
 *   Agent IDs:    organizer-1, coordinator-1, worker-{n}, system
 *   Task IDs:     task_{uuid16}   (generated by backend)
 *   Sandbox IDs:  task-{hash8}-{uuid4}, openhands-{agent}, sandbox-{uuid8}
 */

// ============================================================================
// Well-known Agent IDs (must match backend teaming24/utils/ids.py)
// ============================================================================

export const ORGANIZER_ID = 'organizer-1'
export const COORDINATOR_ID = 'coordinator-1'
export const SYSTEM_ID = 'system'
export const LOCAL_COORDINATOR_NAME = 'local team coordinator'

// ============================================================================
// ID Prefixes (for filtering / detection)
// ============================================================================

export const DEMO_PREFIX = 'demo-'

export function isDemoId(id: string): boolean {
  return id.startsWith(DEMO_PREFIX)
}

// ============================================================================
// Sandbox ID Generators
// ============================================================================

let _fallbackCounter = 0

function randomIdCore(): string {
  const cryptoObj = globalThis.crypto as Crypto | undefined
  if (cryptoObj?.randomUUID) {
    return cryptoObj.randomUUID().replace(/-/g, '')
  }
  if (cryptoObj?.getRandomValues) {
    const bytes = new Uint8Array(16)
    cryptoObj.getRandomValues(bytes)
    return Array.from(bytes, (b) => b.toString(16).padStart(2, '0')).join('')
  }
  _fallbackCounter = (_fallbackCounter + 1) & 0xffff
  return `${Date.now().toString(16)}${_fallbackCounter.toString(16).padStart(4, '0')}`
}

export function randomHex(length = 12): string {
  if (length <= 0) return ''
  let out = ''
  while (out.length < length) {
    out += randomIdCore()
  }
  return out.slice(0, length)
}

export function prefixedId(prefix: string, length = 12, separator = '-'): string {
  const core = randomHex(length)
  if (!prefix) return core
  if (!separator) return `${prefix}${core}`
  return prefix.endsWith(separator) ? `${prefix}${core}` : `${prefix}${separator}${core}`
}

/** Generate a demo sandbox ID (frontend-initiated demos). */
export function demoId(): string {
  return prefixedId(DEMO_PREFIX, 12, '')
}

// ============================================================================
// Generic ID Generator (for frontend-only entities: messages, logs, steps)
// ============================================================================

export function generateId(): string {
  return randomHex(12)
}

/** Generate a temporary ID with optional prefix (UI-only/transient use). */
export function generateTempId(prefix = 'tmp'): string {
  return prefix ? prefixedId(prefix, 12) : randomHex(12)
}
